version: 0.2
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
    artifacts:
      files:
        - '/**/*'
      discard-paths: no
      base-directory: build








# version: 0.2

# phases: 
#     pre_build:
#         commands: 
#             - npm install
#     build:
#         commands:
#             - npm run build
#     artifacts:
#       files:
#         - '/**/*'
#       discard-paths: no
#       base-directory: build