version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*








# version: 0.2

# phases: 
#     pre_build:
#         commands: 
#             - npm install
#     build:
#         commands:
#             - npm run build
#     artifacts:
#       files:
#         - '/**/*'
#       discard-paths: no
#       base-directory: build